feat: chat UI with rsc example
run-llama/LlamaIndexTS pull request #1481
Opened 2024-11-14 09:55 UTC by thucpn

2024-11-14 17:41 UTC, himself65 requested changes

2024-11-14 17:41 UTC, himself65 commented on apps/next/src/components/demo/chat/rsc/ai-action.tsx
> +import { ChatMessage, OpenAIAgent } from "llamaindex";
Do not use llamaindex for now, it has lots of dependencies

2024-11-14 18:30 UTC, himself65 commented on apps/next/src/components/demo/chat/rsc/ai-action.tsx
im not sure, but we don't need really have a backend impletation for document, because it costs the real money from openai. We might need a FakeLLM and some fixed input options in user side in the future

2024-11-15 02:32 UTC, marcusschiesser commented on packages/cloud/package.json
> +    "generate": "openapi-ts",
why this change?

2024-11-15 05:32 UTC, himself65 approved these changes

2024-11-15 05:33 UTC, merged