Add AstraDB Vector Store
run-llama/LlamaIndexTS pull request #249
Opened 2023-12-01 21:27 UTC by mfortman11

Add Vector Store for AstraDB plus examples

2023-12-04 03:35 UTC, marcusschiesser requested changes
Great job! Just some comments concerning the importing of the package. Please have a look

2023-12-04 03:43 UTC, marcusschiesser commented on packages/core/src/storage/vectorStore/AstraDBVectorStore.ts
> +    const keyspace = process.env.ASTRA_DB_NAMESPACE;
alternatively provide config from param obj? e.g.
```
const token = params?.token ?? process.env.ASTRA_DB_APPLICATION_TOKEN;

2023-12-04 17:35 UTC, mfortman11 commented
@marcusschiesser thanks for the feedback all comments have been addressed!

2023-12-05 02:44 UTC, marcusschiesser approved these changes

2023-12-06 22:31 UTC, merged