refactor: restructure documentation
run-llama/LlamaIndexTS pull request #420
Opened 2024-01-23 01:15 UTC by EmanuelCampos

2024-01-24 03:59 UTC, marcusschiesser approved these changes

2024-01-24 04:00 UTC, marcusschiesser commented
@EmanuelCampos LGTM, but can't merge

2024-01-24 09:56 UTC, EmanuelCampos commented
> @EmanuelCampos LGTM, but can't merge

due to conflicts? fixed they now

2024-01-25 01:22 UTC, himself65 commented on apps/docs/docs/examples/chat_engine.md
I'm a little worry about the maintenance of the example code. Could we read raw text from `<rootDir>/examples` and render them?

2024-01-25 01:30 UTC, himself65 requested changes
I will do some change on code example

2024-01-25 01:36 UTC, himself65 approved these changes

2024-01-25 03:22 UTC, merged

2024-01-25 03:22 UTC, marcusschiesser commented
@EmanuelCampos thanks!