define mergePoetryDependencies type
run-llama/LlamaIndexTS pull request #465
Opened 2024-01-27 14:38 UTC by stmtk1

2024-01-28 18:09 UTC, himself65 requested changes

2024-01-28 18:09 UTC, himself65 commented on packages/create-llama/helpers/python.ts
> +  existingDependencies: { [key: string]: Omit<Dependency, "name"> },
Record<string, Omit<Dependency, "name">>

2024-01-28 18:09 UTC, himself65 commented on packages/create-llama/helpers/python.ts
> +    const existingDependencies = tool.poetry.dependencies as {
useless type cast if `fileParsed.tool` is still `any` type

2024-01-29 18:49 UTC, himself65 approved these changes

2024-01-30 03:46 UTC, marcusschiesser approved these changes

2024-01-30 03:47 UTC, merged

2024-01-30 03:47 UTC, marcusschiesser commented
Thanks @stmtk1 !