feat: use batching in vector store index
run-llama/LlamaIndexTS pull request #524
Opened 2024-02-07 08:16 UTC by marcusschiesser

2024-02-07 21:36 UTC, himself65 approved these changes

2024-02-08 02:58 UTC, marcusschiesser commented
don't merge missing the changes to OpenAIEmbedding that @EmanuelCampos and I discussed

2024-02-08 11:03 UTC, EmanuelCampos requested changes
doing some changes on it

2024-02-08 11:59 UTC, EmanuelCampos approved these changes

2024-02-08 11:59 UTC, EmanuelCampos commented
LGTM

2024-02-08 11:59 UTC, merged