Added Language and parsingInstruction to LlamaParseReader + example
run-llama/LlamaIndexTS pull request #779
Opened 2024-04-27 22:00 UTC by InsightByAI

Implemented Language and parsingInstruction to LlamaParseReader and added one example.

A bit hard to test as you can't really get any info from the jobs running on LlamaParse, but adding the LaTeX instruction, see llamaparse_2, did work as expected.
Second try because I'm an idiot and left my API key in the example lol

2024-04-27 22:09 UTC, InsightByAI commented
The example is more or less the implementation of this [Blog Post](https://www.llamaindex.ai/blog/launching-the-first-genai-native-document-parsing-platform) from LlamaIndex

2024-04-28 20:12 UTC, himself65 commented on packages/core/src/readers/LlamaParseReader.ts
> +      body: body,
```suggestion
      body,
```

2024-04-28 20:14 UTC, himself65 requested changes
LGTM, but need some small change

2024-04-28 20:14 UTC, himself65 commented on examples/readers/src/llamaparse_2.ts
> +import fs from "fs";
use `fs/promises`

2024-04-28 20:14 UTC, himself65 commented on examples/readers/src/llamaparse_2.ts
> +  const parsedManga = documents.map((page) => page.text).join("\n\n");
it's good to separate pages using `---`

2024-04-28 21:26 UTC, himself65 approved these changes

2024-04-28 22:00 UTC, himself65 commented
Btw, if you leak api key, please revoke it because commit could be found even you force push

2024-04-28 22:00 UTC, merged

2024-04-29 07:43 UTC, InsightByAI commented
> Btw, if you leak api key, please revoke it because commit could be found even you force push 

Yeah that was the first thing I did lol. Thanks tho!